# Generated by Django 2.2.7 on 2019-11-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sheep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=128)),
                ('lastLocationUpdate', models.CharField(max_length=128)),
                ('lastKnownLat', models.FloatField()),
                ('lastKnownLng', models.FloatField()),
            ],
        ),
    ]
