# Generated by Django 2.2.7 on 2019-11-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheep',
            name='lastLocationUpdate',
            field=models.DateTimeField(),
        ),
    ]
